Repository biocypher/omnipath-secondary-adapter, pull requests merged in 2025-05, with the labels that each got.

#39 Enhanced Documentation, New Features, and Formatting Updates for Omnipath Secondary Adapter
  .gitignore
  README.md
  config/schema_config.yaml
  data_testing/subset_networks_100.tsv
  docker-variables.env
  docker/create_table.sh
  docs_adapter/img/example-neo4j-vis.png
  docs_adapter/img/script-edit-binary.png
  docs_adapter/instructions-ontoweaver-adapters.md
  notebooks/EDA_networks_db.ipynb
  poetry.lock
  pyproject.toml
  scripts/build.sh
  scripts/generate_data_subset_allatonce.sh
  scripts/generate_data_subset_individual.sh
  weave_knowledge_graph.py
  weave_knowledge_graph_backup.py
  weave_knowledge_graph_original.py
Labels: dev: use case

#41 fix: changing the schema graph to enable filter node type on neo4j
  config/biocypher_config_intercell.yaml
  config/schema_config_intercell.yaml
  omnipath_secondary_adapter/adapters/intercell.yaml
  poetry.lock
  pyproject.toml
Labels: bug

#42 Feature/Annotations dev
  config/biocypher_config_annotations.yaml
  config/schema_config_annotations.yaml
  data_testing/subset_annotations_1000.tsv
  notebooks/EDA_annotations.ipynb
  omnipath_secondary_adapter/adapters/annotations.yaml
  poetry.lock
  weave_knowledge_graph.py
Labels: enhancement

#43 Feature/Complexes dev
  config/biocypher_config_complexes.yaml
  config/schema_config_complexes.yaml
  notebooks/EDA_complex_db.ipynb
  omnipath_secondary_adapter/adapters/complexes.yaml
  weave_knowledge_graph.py
Labels: enhancement
